project_name: shipcaps-kubectl
release:
  github:
    owner: redradrat
    name: shipcaps-kubectl
builds:
  - id: shipcaps-kubectl
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/shipcaps/main.go
    ldflags: -s -w
      -X github.com/redradrat/shipcaps-kubectl/pkg/version.version=
archives:
  - id: shipcaps-kubectl
    builds:
    - shipcaps-kubectl
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
