apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: shipcaps-kubectl
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/redradrat/shipcaps-kubectl/releases/download/v0.1.0/shipcaps-kubectl_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./shipcaps-kubectl"
      to: "."
    - from: LICENSE
      to: "."
    bin: "shipcaps-kubectl"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/redradrat/shipcaps-kubectl/releases/download/v0.1.0/shipcaps-kubectl_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./shipcaps-kubectl"
      to: "."
    - from: LICENSE
      to: "."
    bin: "shipcaps-kubectl"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/redradrat/shipcaps-kubectl/releases/download/v0.1.0/shipcaps-kubectl_windows_amd64.zip
    sha256: ""
    files:
    - from: "/shipcaps-kubectl.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "shipcaps-kubectl.exe"
  shortDescription: A new shipcaps
  homepage: https://github.com/redradrat/shipcaps-kubectl
  caveats: |
    Usage:
      $ kubectl shipcaps-kubectl

    For additional options:
      $ kubectl shipcaps-kubectl --help
      or https://github.com/redradrat/shipcaps-kubectl/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
